Add inet datatype
gluesql/gluesql pull request #1080
Opened 2023-02-01 02:12 UTC by pythonbrad

2023-02-01 08:23 UTC, pythonbrad commented
I think that this pull request is ready for review. ✍🏿

2023-02-02 00:23 UTC, panarch requested changes
Thanks a lot 👍 
All the implementation codes look great.

Before merging this
could you add some more unit tests?

![image](https://user-images.githubusercontent.com/2025065/216199894-fcb4da21-9c88-4501-b7c1-48615e3cca42.png)
![image](https://user-images.githubusercontent.com/2025065/216199971-7193e9e8-081a-4781-982e-72ab68277039.png)

It is enough to see the file lists in `Changes Missing Coverage` and the lines which are marked as `NEW`.

2023-02-02 00:23 UTC, panarch commented on core/src/data/value/convert.rs
> +            net::{Ipv4Addr, Ipv6Addr},
nit. we can merge this `net::{IpAddr, Ipv4Addr, Ipv6Addr}`

2023-02-07 05:18 UTC, panarch approved these changes
Looks all great 👍 👍 👍 
So pleased to see the new data type :D 
Thanks a lot!

2023-02-07 05:19 UTC, merged