[Function] Implement REPLACE function
gluesql/gluesql pull request #1266
Opened 2023-07-10 14:36 UTC by ChobobDev

resolves #1146

2023-07-10 15:26 UTC, ChobobDev commented
I think I am ready for review!

2023-07-11 11:40 UTC, zmrdltl approved these changes
Thanks for adding the function, now GlueSQL has a new feature!

2023-07-11 13:22 UTC, devgony requested changes

2023-07-11 14:17 UTC, ChobobDev commented on test-suite/src/function/replace.rs
> +            Ok(select_with_null!(test; Value::Null)),
I think this really is a good idea, i did not realize we have a new conventions for test-suites!
I will work on them ASAP

2023-07-12 10:45 UTC, devgony approved these changes
Thank you for writing fine-grained test cases 👍🏼

2023-07-12 11:09 UTC, panarch approved these changes
Looks all great!
Also thanks a lot for adding well documented integration tests.

2023-07-12 11:09 UTC, merged