feat: implement `LENGTH` function
gluesql/gluesql pull request #1298
Opened 2023-07-15 07:21 UTC by jopemachine

Fixes #1297.

2023-07-16 05:07 UTC, ever0de requested changes
https://coveralls.io/builds/61364317

Please refer to the coveralls and write test cases for the uncovered parts.

2023-07-16 05:07 UTC, ever0de commented on test-suite/src/function/length.rs
> +        expected: Ok(Payload::Select { labels: vec!["LENGTH('Hello.')".to_owned()], rows: vec![vec![Value::U64(6)]] })
Let's use the `select!` macro to write the expected part like any other test case.

2023-07-16 05:07 UTC, ever0de commented on test-suite/src/function/length.rs
> +        expected: Ok(Payload::Select { labels: vec!["LENGTH('Hello.')".to_owned()], rows: vec![vec![Value::U64(6)]] })
https://github.com/gluesql/gluesql/blob/29f4128d38a11848cf123c60dd6b9b2f4076cbd7/test-suite/src/basic.rs#L44-L51

2023-07-17 15:00 UTC, ever0de approved these changes
Looks good to me, what does anyone else think?

2023-07-17 15:04 UTC, panarch approved these changes
Looks all great! Thanks a lot for the contribution 👍 👍

2023-07-17 15:04 UTC, merged