Remove eval_to_{int|float..} macro uses in core/../evaluate/function.rs,
gluesql/gluesql pull request #1361
Opened 2023-08-04 06:11 UTC by panarch

Update all function return types from Result to ControlFlow.
Replace eval_to_{..} macros to normal functions.
Except for NULL break handling, this does not affect existing business logics.

2023-08-05 07:46 UTC, ever0de requested changes

2023-08-05 07:46 UTC, ever0de commented on core/src/executor/evaluate/function.rs
> +            left.concat(right).break_if_null().map(Some)
```suggestion
        .try_fold(None, |left: Option<Evaluated>, right| match left {
            None => Continue(Some(right)),
            Some(left) => left.concat(right).break_if_null().map(Some),
        })?;
```

2023-08-05 07:46 UTC, ever0de commented on core/src/executor/evaluate/function.rs
> +    let value: Value = value.try_into().break_if_null()?;
```suggestion
    let expr = expr.try_into().break_if_null()?;
    let value = value.try_into().break_if_null()?;
```

2023-08-05 07:46 UTC, ever0de commented on core/src/executor/evaluate/function.rs
> +    let value: Value = value.try_into().break_if_null()?;
Please also remove the similar `type annotation` below

2023-08-05 07:46 UTC, ever0de commented on core/src/executor/evaluate/mod.rs
> +        Function::Pi() => return Ok(Evaluated::from(Value::F64(std::f64::consts::PI))),
```suggestion
        Function::Pi() => return Ok(Evaluated::Value(Value::F64(std::f64::consts::PI))),
```

2023-09-23 07:30 UTC, devgony approved these changes

2023-09-23 07:59 UTC, merged