Implement DEDUP function
gluesql/gluesql pull request #1430
Opened 2023-10-15 08:00 UTC by jinlee0

resolves #1426

2023-10-15 13:02 UTC, panarch requested changes

2023-10-15 13:02 UTC, panarch commented on core/src/executor/evaluate/function.rs
> +    let result = list.into_iter().dedup_by(|a, b| a == b).collect::<Vec<_>>();
everything else looks nice!

2023-10-15 13:29 UTC, zmrdltl reviewed
resolve #1426

2023-10-21 07:49 UTC, jinlee0 commented
Sorry, I'm late

2023-10-29 02:37 UTC, panarch approved these changes
Looks all nice :D Thanks a lot 👍

2023-10-29 02:38 UTC, merged