test: add test cases for data selection and data projection
gluesql/gluesql pull request #1461
Opened 2024-02-25 07:39 UTC by sanghee4346

2024-02-25 08:12 UTC, devgony requested changes

2024-02-25 08:12 UTC, devgony commented on test-suite/src/ast_builder/statements/querying/data_selection_and_projection.rs
> +        5   "Eve".to_owned()   50
You'd better format lines according to this example
```rs
id  | num | name
I64 | I64 | Str;
1     2     "Hello".to_owned();
1     9     "World".to_owned();
3     4     "Great".to_owned();
4     7     "Job".to_owned()
```

2024-02-25 08:29 UTC, devgony requested changes

2024-02-25 08:29 UTC, devgony commented on test-suite/src/ast_builder/statements/querying/data_selection_and_projection.rs
> +        5     50   "Eve".to_owned()
```suggestion
        2     30    "Bob".to_owned();
        3     30    "Carol".to_owned();
        4     50    "Dave".to_owned();
        5     50    "Eve".to_owned()
```

2024-05-04 07:52 UTC, devgony approved these changes
Thank you for contribution 👍🏼

2024-05-04 08:02 UTC, panarch approved these changes
Looks nice! Thanks a lot for the contribution 👍

2024-05-04 08:02 UTC, merged