Add functions: ASIN(), ACOS(), ATAN()
gluesql/gluesql pull request #296
Opened 2021-08-18 10:13 UTC by boomkim

Add `ASIN()`, `ACOS()`, `ATAN()` functions. 
These functions support numeric string literals and boolean and floating numbers.
resolve #285 

referenced @maruoovv 's [pull request](https://github.com/gluesql/gluesql/pull/289) a lot.

2021-08-18 11:20 UTC, boomkim commented
Let me fix clippy error and pull request again.

2021-08-18 11:21 UTC, boomkim commented
Resolved clippy error.

2021-08-19 11:32 UTC, panarch requested changes
Changes are simple and straightforward to look around.
Only change requests are about the specifications.
Thanks! 👍 👍 👍

2021-08-19 11:32 UTC, panarch commented on src/executor/evaluate/error.rs
> +    OutOfRange(String),
Ok, here let's simply depend on Rust compiler.
Rust compiler will return `NaN` and we can use that rather than returning explicit error.

2021-08-19 11:32 UTC, panarch commented on src/executor/evaluate/mod.rs
> +                _ => None,
Now, let's make the spec clear.

You can only accept three types; `F64`, `I64` and `Null`.
Except for these three types, `FunctionReuqiresFloatValue` can be the one to return.
`F64` - we can use directly.
`I64` - `as f64` to cast and we can use that.
`Null` -> then return value becomes also null.

2021-08-28 04:43 UTC, panarch approved these changes
Everything looks great, thanks! 👍 👍 👍

2021-08-28 04:43 UTC, merged