Lpad rpad
gluesql/gluesql pull request #311
Opened 2021-08-21 15:27 UTC by No-YE

resolve #269 

Implement Lpad and Rpad functions.
- ` LPAD(string TEXT, length INTEGER, fill TEXT) -> TEXT`
  - Add `fill`(a space by default) to the left of `string`. If `string` is longer than `length`, it shorten to `length`.
- `RPAD(string TEXT, length INTEGER, fill TEXT) -> TEXT`
  - Add `fill`(a space by default) to the right of `string`. If `string` is longer than `length`, it shorten to `length`.

2021-08-22 05:36 UTC, panarch requested changes
Implementation codes look really, really good, thanks! 👍
There's an only single request about adding more test cases.

2021-08-22 05:36 UTC, panarch commented on src/executor/evaluate/mod.rs
> +                    }
There are three `Ok(Evaluated::from(Value::Null)` and a single `Err(..)` and these are not tested.
We need to have test cases for them.

2021-08-23 13:28 UTC, No-YE commented
@panarch Thank you for your review. I added some tests as you said.

2021-08-23 14:05 UTC, panarch approved these changes
Nevertheless there were lots of code conflicts to resolve due to PR merges, thanks for updating so nicely to fit to the new codes.
Thanks!! merging 👍 👍 👍

2021-08-23 14:05 UTC, merged