Support CTAS(Create Table As Select ~) statement enhancement
gluesql/gluesql pull request #414
Opened 2021-11-24 09:55 UTC by devgony

# 🚧 This PR is a draft yet
# Support CTAS(Create Table As Select ~) statement enhancement(#404)
- [x] Add a test case: [src/tests/alter/create_table.rs](src/tests/alter/create_table.rs)
- [x] Add `source` to translate if there is query statements: [src/translate/mod.rs](src/translate/mod.rs)
- [x] Get `source` from ast: [src/ast/mod.rs](src/ast/mod.rs)
- [x] Pass `source` to executor: [src/executor/execute.rs](src/executor/execute.rs)
- [ ] ⏳ Implement CTAS
  - [x] Get source table's schema
  - [x] Create new table with the source schema
  - [ ] Insert data from source to new table
  - [ ] Clear redundant and repetitive code
 - [ ] Add more test cases

2021-12-01 12:34 UTC, panarch commented on src/executor/alter/table.rs
> +    }?;
```rust
let (storage, target_table_name) = get_name(name).try_self(storage)?;               
let schema = (|| async {                                                            
    let target_columns_defs = match source.as_ref().map(AsRef::as_ref) {            
        Some(Query {                                                                
            body: SetExpr::Select(select_query),                                    
            ..                                                                      
        }) => {                                                                     
            let TableFactor::Table {                                                
                name: source_name, ..                                               
            } = &select_query.from.relation;                                        
                                                                                    
            let table_name = get_name(source_name)?;                                
            let schema = storage.fetch_schema(table_name).await?;                   
                                                                                    
            let Schema {                                                            
                column_defs: source_column_defs,                                    
                ..                                                                  
            } = schema.ok_or_else(|| -> Error {                                     
                FetchError::TableNotFound(table_name.to_owned()).into()             
            })?;                                                                    
                                                                                    
            source_column_defs                                                      
        }                                                                           
        _ => column_defs.to_vec(),                                                  
    };                                                                              
                                                                                    
    let schema = Schema {                                                           
        table_name: target_table_name.to_string(),                                  
        column_defs: target_columns_defs,                                           
        indexes: vec![],                                                            
    };                                                                              
                                                                                    
    for column_def in &schema.column_defs {                                         
        validate(column_def)?;                                                      
    }                                                                               
                                                                                    
    match (                                                                         
        storage.fetch_schema(&schema.table_name).await?,                            
        if_not_exists,                                                              
    ) {                                                                             
        (None, _) => Ok(Some(schema)),                                              
        (Some(_), true) => Ok(None),                                                
        (Some(_), false) => {                                                       
            Err(AlterError::TableAlreadyExists(schema.table_name.to_owned()).into())
        }                                                                           
    }                                                                               
})()                                                                                
.await;                                                                             

let (storage, schema) = schema.try_self(storage)?;
let storage = match schema {                      
    Some(schema) => storage                       
        .insert_schema(&schema)                   
        .await                                    
        .map(|(storage, _)| storage)?,            
    None => storage,                              
};                                                
```

2021-12-01 15:46 UTC, ever0de commented on src/executor/alter/table.rs
> +            .try_self(storage)?;
You can simplify it by using `async + scope`

```rust
            let (storage, rows) =
                async { select(&storage, &query, None).await?
                    .try_collect().await }
                    .await
                    .try_self(storage)?;
```

2021-12-06 12:55 UTC, panarch requested changes
There's only a very tiny comment.
Everything else looks awesome, thanks a lot 👍

2021-12-06 13:29 UTC, panarch approved these changes
👍 👍 👍

2021-12-06 13:29 UTC, merged