implement f32
gluesql/gluesql pull request #688
Opened 2022-07-28 13:29 UTC by woojinnn

## Work
Implementation of issue [#623](https://github.com/gluesql/gluesql/issues/623)

## Need your help:  
There are some loss of information while casting, which is expected behavior in Rust.  
Should we endure this issue?  
E.g., value `1234567890` is casted to `1234568000`.

2022-08-08 11:30 UTC, panarch requested changes
Thanks a lot, let's add some tests for covering newly added lines.

Coveralls report would be quite useful.
You can click the link and that will show uncovered line with code changes

![image](https://user-images.githubusercontent.com/2025065/183408160-af6768ce-64dc-4383-a4d4-09a6b033e139.png)

e.g.
![image](https://user-images.githubusercontent.com/2025065/183408316-7b2c95cf-7f1a-41c6-a873-61233b555632.png)

2022-08-08 11:30 UTC, panarch commented on core/src/data/value/json.rs
> +            Value::F32(v) => Ok(JsonValue::Number(JsonNumber::from_f64(v as f64).unwrap())),
1. We can use this
https://docs.rs/serde_json/latest/serde_json/value/enum.Value.html#impl-From%3Cf32%3E-for-Value

`Ok(v.into())` would be enough

2. unit test for `Value::F32` to `JsonValue::Number`

2022-08-08 11:30 UTC, panarch commented on core/src/data/key.rs
>              F64(_) => Err(KeyError::FloatTypeKeyNotSupported.into()),
Same error so we can merge this into same branch
`F32(_) | F64(_) => Err(KeyError::FloatTypeKeyNotSupported.into()),`

2022-08-08 11:30 UTC, panarch commented on core/src/data/value/mod.rs
> +            Value::F32(_) => Some(DataType::Float32),
There's an unit test with `get_type`, we can add `F32` test to that.

2023-04-08 14:11 UTC, pythonbrad commented
@woojinnn, please Is the implementation complete?

2023-04-09 15:05 UTC, pythonbrad commented
@woojinnn, please Is the implementation complete?

2023-04-09 15:23 UTC, woojinnn commented
@pythonbrad Nah. Feel free to take this issue if you're interested

2023-05-06 06:19 UTC, ever0de commented
closed by #1145

2023-05-06 06:19 UTC, closed without merging