[AST] Implement to_sql func for OrderByExpr, Values
gluesql/gluesql pull request #812
Opened 2022-09-03 11:27 UTC by CEOJINSUNG

Resolve #809

2022-09-03 11:50 UTC, ever0de approved these changes
Looks good :+1:

2022-09-04 04:36 UTC, panarch requested changes
Current ToSql impl of `VALUES` is different from what it actually does.
e.g.
```rust
VALUES (1, NULL), (2, 'a'), (3, 4)
```

More information is here in `test-suite/ values.rs`
ref. https://github.com/CEOJINSUNG/gluesql/blob/features/query-to-sql/test-suite/src/values.rs

2022-09-17 05:07 UTC, panarch commented on core/src/ast/mod.rs
> +                    _column.to_sql()
Now the `_column` is being used, so we can remove `_` underscore prefix.
`column.to_sql()` would be enough

2022-09-17 06:58 UTC, panarch approved these changes
Awesome! Looks all nice, now `CREATE INDEX` ToSQL impl has completed :D Thanks a lot!

2022-09-17 06:58 UTC, merged